### ISSUE TITLE
Build Pipeline

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/website#1]
We need a build pipeline for the High Fives website. It's usually a good idea to do this first. I typically use Heroku for app hosting, but if someone has a better idea?

__requirements__
* Continuous Delivery, from pull request to production
* Staging/Branch and preview location, all commits to staging
* Production/master, only tagged commits
* BDD Testing (would be nice, cucumber?)
* TDD Testing (JEST already incorporated, maybe coverage rules?)
* Accessibility, Axe in the pipeline, non accessible commits will not make it.

**Comment by jordanpapaleo** [comment]
- Should we break these into smaller tasks?
- Where is the Continuous Deilvery deliver to

**Comment by MoonTahoe** [comment]
Yea, we probably should break these down. I like to use heroku for hosting but we're down for any other suggestions. If we break any of this functionality out into npm there is a [high fives foundation](https://www.npmjs.com/org/highfivesfoundation) on npm that we can use.

**Comment by jordanpapaleo** [comment]
I like heroku.  Post Nov 6 when I come back to life I'd love to help here
