### ISSUE TITLE
Remove all .css files

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/website#15]
Let's try to use Styled Components across the board. This means removing the `index.css` file from the root and placing the styles found there in the `index.js` using styled components:

__Example of `injectGlobal` form styled Compoennts___
```javascript
import { injectGlobal } from 'styled-components'

injectGlobal`
  html, 
  body, 
  #root {
        height: 100%;
  }
  body {
    display: flex;
    min-height: 100%;
    height: auto;
    padding: 0;
    margin: 0;
  }
  #root {
    flex-grow: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100%;
    height: auto;
  }
  h1, h2, h3, h4, p, td, span, div {
    padding: 0;
    margin: 0;
  }
`
```

**Comment by hakabuk** [comment]
I'd like to do this one, if it's up for grabs

**Comment by eveporcello** [comment]
Thanks so much, @hakabuk! It's very up for grabs and all yours. Let me know if you have any questions along the way!

**Comment by hakabuk** [comment]
I tried finding the `index.css` file and couldn't, @eveporcello . I did find a `global.css` which only includes a box sizing style to all elements in the projects. Not sure how to proceed here, but I'm happy to be unassigned if anyone else is interested

**Comment by MoonTahoe** [comment]
I think we took care of this one at the hack-a-thon on Saturday...  Should have closed it.
