### ISSUE TITLE
Create react script

### ISSUE THREAD

**Issue by jordanpapaleo** [HighFivesFoundation/website#3]
Before we get too deep in building out this I want to bring up that the create-react script does not support redux and a ton of other things.

We built a custom script that can be used to spin up a react app with a lot of extras in it.

**Comment by MoonTahoe** [comment]
What is that? cc-react-scripts or something?  Yea, I'd love to use it.

I think I got ahead of myself with this issue, and we need to take a step back and think about Issue #4. It is starting to look like GraphQL and Apollo will be the tools of choice. Do you have a script that works with all of the fun things that we want to incorporate?

**Comment by jordanpapaleo** [comment]
https://github.com/clearcapital/cc-react-scripts

Its out custom config create react app
