### ISSUE TITLE
Add GraphQL Schema Diff to Github Checks

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/website#39]
Apollo has a tool that we can add to the github checks that checks for changes to the schema. Let's incorporate this tool into our pipeline.

**Comment by rockchalkwushock** [comment]
I'll read up on this and see how we can set it up with the project.

**Comment by MoonTahoe** [comment]
We've decided to move the schema and the mocks into a separate project that we can install across projects with npm. This task has been moved to: highfivesfoundation/schema-provider#3.
