### ISSUE TITLE
Feature: Home Page

### ISSUE THREAD

**Issue by eveporcello** [HighFivesFoundation/website#5]
Feature: Home Page
=======
The home page of the website will show the most important information about the High Fives Foundation and will introduce visitors to the organization.  

Requirements
-------
- [ ] The home page must look great on mobile devices.
- [ ] The home page must prioritize accessibility and follow a11y best practices.
- [ ] The home page must include a "Donate to High Fives" section.
- [ ] Users of the home page must be able to navigate the page using only their keyboard.
- [ ] Users must be able to apply to become an Athlete easily and quickly.
- [ ] Users must see a High Fives summary and Athlete profile section.
- [ ] Users must be able to access news stories and events from the home page.
- [ ] The home page should use image loading best practices to make the initial file load as fast as possible.

User Stories
--------
[List of Website Actors](https://github.com/HighFivesFoundation/website/wiki/High-Fives-Website-Actors)

### Anonymous Web User
1. I should be able to view all web content from any device.
2. I should be able to donate to High Fives easily and quickly.
3. I should be able to navigate the site using only my keyboard.
4. I should be able to learn about High Fives via a summary and athlete profile section.
5. I should be able to view the most recent News and Events.
6. I should be able to quickly find the application process to become a High Fives Athlete.

### Athlete
same as above

### Member
same as above

### Administrator
same as above

### Developer
same as above

### Internal
same as above

Related Wireframes
-------------
* [Wireframes](https://app.moqups.com/eporcello/BTrdKJSG6L/view)
* [Mobile Wireframes](https://app.moqups.com/eporcello/RYisM4vc9E/view)

**Comment by MoonTahoe** [comment]
We've created a new feature for this found at #64
